security:
    password_hashers:
        App\Entity\User\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/users/login
            security: false
        api:
            pattern: ^/
            stateless: true
            provider: app_user_provider
            jwt: ~
            access_denied_handler: App\Security\AccessDeniedHandler

    access_control:
        - { path: ^/users/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
